### ISSUE TITLE
Create a sub-menu screen

### ISSUE THREAD

**Issue by cezeilo** [cse442-spring-2020-offering/cse442-semester-project-keyblade-hero-3#13]
This screen appears after pressing the 'View Menu' button on the main screen for a campus dining service. What should show now is a menu for whichever place was clicked, along with when they are open, and there should be text that notifies the user if the place is open or closed currently. 

In addition, when you choose items from the sub-menu they should appear in a cart that once you click the 'order' button, you will be brought to the payment screen.

**Comment by lockhaj1** [comment]
Extended into Sprint 2 as functionality not in place and currently place holder menu items.
