### ISSUE TITLE
Payment screen

### ISSUE THREAD

**Issue by cezeilo** [cse442-spring-2020-offering/cse442-semester-project-keyblade-hero-3#15]
Screen where the total amount is present and the user will specify how they will pay. A button will be present here which when pressed, processes the order. 

Task Test:
1. Display Payment Screen.
2. Display Total price from menu items.
3. Have option to confirm or cancel order.
4. Have  option to input credit card information.

**Comment by lockhaj1** [comment]
Added to sprint 2 as functionality is not in place
